import { ImageResponse } from "next/og";
import { getDict } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n/config";

/**
 * Shared Open Graph / Twitter card renderer — "wordmark minimal" concept.
 * 1200×630 PNG generated by Satori. Localised tagline (FR at root, EN under
 * /en). The site's display font (Clash Display) is woff2-only, which Satori
 * can't read, so the wordmark uses Space Grotesk — the closest geometric match
 * — fetched as TTF from Google Fonts, with a graceful fallback to the default.
 */

export const OG_SIZE = { width: 1200, height: 630 };

const HOLO = "linear-gradient(108deg, #22d3ee, #8b5cf6, #e94bd0)";

async function googleFont(weight: number): Promise<ArrayBuffer | null> {
  try {
    const css = await fetch(`https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@${weight}`, {
      headers: { "User-Agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)" },
    }).then((r) => r.text());
    const url = css.match(/src:\s*url\((https:[^)]+)\)\s*format\(['"]?(?:truetype|opentype)['"]?\)/)?.[1];
    if (!url) return null;
    return await fetch(url).then((r) => r.arrayBuffer());
  } catch {
    return null;
  }
}

export async function renderOgImage(locale: Locale): Promise<ImageResponse> {
  const dict = getDict(locale);
  const [bold, regular] = await Promise.all([googleFont(700), googleFont(400)]);
  const fonts = [
    bold ? { name: "Space Grotesk", data: bold, weight: 700 as const, style: "normal" as const } : null,
    regular ? { name: "Space Grotesk", data: regular, weight: 400 as const, style: "normal" as const } : null,
  ].filter((f): f is NonNullable<typeof f> => f !== null);

  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "#0B0E14",
          color: "#ffffff",
          fontFamily: "Space Grotesk, sans-serif",
        }}
      >
        <div style={{ fontSize: 24, letterSpacing: 7, color: "#7c8499", fontWeight: 400 }}>
          EXPECTED VALUE · POKÉMON TCG
        </div>
        <div style={{ display: "flex", fontSize: 150, fontWeight: 700, letterSpacing: -5, marginTop: 20 }}>
          <span>Poké</span>
          <span
            style={{
              backgroundImage: HOLO,
              backgroundClip: "text",
              WebkitBackgroundClip: "text",
              color: "transparent",
            }}
          >
            EV
          </span>
        </div>
        <div style={{ width: 150, height: 8, borderRadius: 8, marginTop: 30, backgroundImage: HOLO }} />
        <div
          style={{
            display: "flex",
            fontSize: 40,
            lineHeight: 1.35,
            color: "#aab2c5",
            marginTop: 34,
            maxWidth: 860,
            textAlign: "center",
            fontWeight: 400,
          }}
        >
          {dict.common.tagline}
        </div>
        <div style={{ position: "absolute", bottom: 48, fontSize: 26, letterSpacing: 3, color: "#7c8499", fontWeight: 400 }}>
          pokeev.com
        </div>
      </div>
    ),
    { ...OG_SIZE, fonts: fonts.length ? fonts : undefined },
  );
}
