import { ImageResponse } from "next/og";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { getDict } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n/config";

/**
 * Shared Open Graph / Twitter card renderer — "wordmark minimal" concept.
 * 1200×630 PNG generated by Satori, using the site's REAL brand fonts (Clash
 * Display for the wordmark, Satoshi for everything else) bundled as TTF in
 * src/assets/og — the same fonts as the header and the dynamic /api/og card, so
 * every share surface is visually identical (and matches the @pokeev.tcg logo).
 */

export const OG_SIZE = { width: 1200, height: 630 };

const HOLO = "linear-gradient(108deg, #22d3ee, #8b5cf6, #e94bd0)";

async function loadFonts() {
  const dir = join(process.cwd(), "src", "assets", "og");
  const [clash, satoshi] = await Promise.all([
    readFile(join(dir, "clash-display-700.ttf")),
    readFile(join(dir, "satoshi-500.ttf")),
  ]);
  return [
    { name: "Clash", data: clash, weight: 700 as const, style: "normal" as const },
    { name: "Satoshi", data: satoshi, weight: 500 as const, style: "normal" as const },
  ];
}

export async function renderOgImage(locale: Locale): Promise<ImageResponse> {
  const dict = getDict(locale);
  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background: "#0B0E14",
          color: "#ffffff",
          fontFamily: "Satoshi, sans-serif",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            background:
              "radial-gradient(circle at 50% 43%, rgba(139,92,246,0.32), rgba(34,211,238,0.10) 38%, rgba(11,14,20,0) 62%)",
          }}
        />
        <div style={{ fontSize: 24, letterSpacing: 7, color: "#8a93a6", fontWeight: 500 }}>
          EXPECTED VALUE · POKÉMON TCG
        </div>
        <div style={{ display: "flex", fontFamily: "Clash", fontSize: 168, fontWeight: 700, letterSpacing: -4, marginTop: 18 }}>
          <span style={{ color: "#E8ECF4" }}>Poké</span>
          <span
            style={{
              backgroundImage: HOLO,
              backgroundClip: "text",
              WebkitBackgroundClip: "text",
              color: "transparent",
            }}
          >
            EV
          </span>
        </div>
        <div style={{ width: 168, height: 8, borderRadius: 8, marginTop: 26, backgroundImage: HOLO }} />
        <div
          style={{
            display: "flex",
            fontSize: 38,
            lineHeight: 1.35,
            color: "#aab2c5",
            marginTop: 32,
            maxWidth: 880,
            textAlign: "center",
            fontWeight: 500,
          }}
        >
          {dict.common.tagline}
        </div>
        <div style={{ position: "absolute", bottom: 48, fontSize: 26, letterSpacing: 3, color: "#7c8499", fontWeight: 500 }}>
          pokeev.com · @pokeev.tcg
        </div>
      </div>
    ),
    { ...OG_SIZE, fonts: await loadFonts() },
  );
}
